on:
  workflow_call:
    inputs:
      version:
        required: true
        description: 'Version to deploy'
        type: string
    secrets:
      github-token:
        required: true
        description: 'GitHub token with permission to create tags for commits that update workflows'
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        with:
          token: ${{ secrets.github-token }}
      - name: Create tag
        env:
          GH_TOKEN: ${{ secrets.github-token }}
          VERSION: ${{ inputs.version }}
        run: |
          gh auth setup-git
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "baynezy@gmail.com"
          git tag -a "$VERSION" -m "Version $VERSION created via GitHub Actions"
          git push origin "$VERSION"
